name: Expo Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Configure EAS
        run: eas login --token ${{ secrets.EAS_TOKEN }}

      - name: Build Android
        run: eas build --profile development --platform android --non-interactive
