name: Expo Build

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Configure EAS
        run: echo ${{ secrets.EAS_TOKEN }} | eas login

      - name: Validate EAS Configuration
        run: eas diagnostics
        
      - name: Prepare Build (without executing)
        run: echo "Build preparation complete. Skipping actual build due to EAS quota limitations."
        
      # Commented out actual build step until quota resets
      # - name: Build Android
      #   run: eas build --profile development --platform android --non-interactive
