name: Test Secrets

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check Secret Availability
        run: |
          if [ -n "${{ secrets.SUPABASE_URL }}" ]; then
            echo "✓ SUPABASE_URL is set"
          fi
          if [ -n "${{ secrets.SUPABASE_KEY }}" ]; then
            echo "✓ SUPABASE_KEY is set"
          fi
          if [ -n "${{ secrets.SUPABASE_SERVICE_KEY }}" ]; then
            echo "✓ SUPABASE_SERVICE_KEY is set"
          fi
          if [ -n "${{ secrets.DEEPSEEK_API_KEY }}" ]; then
            echo "✓ DEEPSEEK_API_KEY is set"
          fi
          if [ -n "${{ secrets.SENTRY_DSN }}" ]; then
            echo "✓ SENTRY_DSN is set"
          fi
